remote_theme: just-the-docs/just-the-docs
logo: assets/img/esohinformatics_gitlogo.png
favicon_ico: assets/img/favicon.ico




baseurl: ""
url: "https://esohkevin.github.io/siaImputationService/"
repository: esohkevin/siaImputationService

permalink: pretty

color_scheme: "dark"