remote_theme: just-the-docs/just-the-docs
logo: assets/img/esohinformatics_gitlogo.png
favicon_ico: assets/img/favicon.ico




baseurl: "https://esohkevin.github.io/"
#url: "https://sia-imputation-service.com"
#repository: esohkevin/siaImputationService

#permalink: pretty

color_scheme: "dark"